name: Java CI with Maven

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Create .env file
      run: |
        echo "PLAID_CLIENT_ID=${{ secrets.PLAID_CLIENT_ID }}" >> .env
        echo "PLAID_SECRET=${{ secrets.PLAID_SECRET }}" >> .env
        
    - name: Build with Maven
      run: mvn clean install
      
    - name: Run tests
      run: mvn test
